id: I647D7CBC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-10T18:43:00+00:00'
last_modified: '2022-06-16T07:56:54.543941+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13126
  title: བསྟན་འགྱུར། ༼པེ་ཅིང་།༽
  author: ''
  base:
    7E4F:
      image_group_id: I1KG13170
      title: ''
      total_pages: ''
      order: 1
      base_file: 7E4F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
